-- Creating the tables
CREATE TABLE EMP (
	EMPNO NUMERIC(6),
	EFNAME VARCHAR(20),
	ELNAME VARCHAR(20),
	JOB VARCHAR(10),
	DEPTNAME VARCHAR(10),
	DEPTNO NUMERIC(2),
	ECITY VARCHAR(10),
	SAL NUMERIC(7, 2),
	MANAGERNAME VARCHAR(10),
	MANAGERNO INT(20),
	foreign key (DEPTNO) references DEPT(DEPTNO)
);

CREATE TABLE DEPT (
	DEPTNO NUMERIC(2),
	DNAME VARCHAR(10),
	LOC VARCHAR(10),
	LOCID NUMERIC(5)
);

CREATE TABLE JOB_GRADES (
	JOB VARCHAR(10) PRIMARY KEY,
	HIRE_DATE DATETIME,
	GRADE VARCHAR(2)
);

-- 1)
ALTER TABLE EMP
DROP COLUMN DEPTNAME,
ADD PRIMARY KEY (EMPNO),
ADD FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO),
ADD FOREIGN KEY (JOB) REFERENCES JOB_GRADES(JOB);


INSERT INTO DEPT
VALUES (1, 'CSE', 'LHC', 1),
	(2, 'ECE', 'Food Court', 2),
	(3, 'MME', 'Orion', 3),
	(4, 'CHEM', 'Orion', 3),
	(5, 'ICE', 'Food Court', 2);

INSERT INTO EMP
VALUES (1, 'King', 'XYZ', 'King', 1, 'Singapore', 100000, '', NULL),
	(2, 'Adarsh', 'Patel', 'Student', 1, 'Trichy', 1000, 'XYZ', 1),
	(3, 'Ashutosh', 'Pandey', 'Student', 2, 'Trichy', 1000, 'XYZ', 1),
	(4, 'Aditya', 'Kumar', 'Student', 3, 'Toronto', 1000, 'XYZ', 1),
	(5, 'Anoop', 'Kumar', 'Student', 2, 'Trichy', 1000, 'XYZ', 1),
	(6, 'Karan', 'Purswani', 'Student', 5, 'Toronto', 1000, 'XYZ', 1),
	(7, 'Omkar', 'Sardesai', 'Teacher', 4, 'Trichy', 10000, 'XYZ', 1),
	(8, 'Ravi', 'Sankar', 'Staff', 4, 'Toronto', 0, 'XYZ', 1),
	(9, 'Ashutosh', 'Singh', 'Student', 4, 'Trichy', 1000, 'XYZ', 1);

INSERT INTO JOB_GRADES
VALUES ('King', '1999-10-10 12:00', 'A'),
	('Student', '2012-08-11 12:00', 'B'),
	('Teacher', '2019-12-12 12:00', 'C');

-- 2)
SELECT EMP.ELNAME, EMP.DEPTNO, DEPT.DNAME 
FROM EMP 
INNER JOIN
DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

-- 3)
SELECT DISTINCT EMP.JOB, DEPT.LOC
FROM EMP
INNER JOIN
DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DEPT.DNAME = 'MME';

-- 4)
SELECT EMP.ELNAME, DEPT.DNAME, DEPT.LOCID, EMP.ECITY
FROM EMP
INNER JOIN
DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL > 0;

-- 5)
SELECT EMP.ELNAME, DEPT.DNAME
FROM EMP
INNER JOIN
DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.ELNAME LIKE '%a%';

-- 6)
SELECT EMP.ELNAME AS 'Emp#', EMP.EMPNO,
EMP.MANAGERNAME AS 'Mgr#', EMP.MANAGERNO
FROM EMP;

-- 7)
SELECT EMP.ELNAME, EMP.JOB, DEPT.DEPTNO, DEPT.DNAME
FROM EMP
INNER JOIN
DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.ECITY = 'Toronto';

-- 8)
SELECT EMP.ELNAME AS 'Emp#', EMP.EMPNO,
EMP.MANAGERNAME AS 'Mgr#', EMP.MANAGERNO
FROM EMP
ORDER BY EMP.EMPNO;

-- 9) Given emp = 'Ravi'
SELECT EMP.ELNAME, DEPT.DEPTNO
FROM EMP
INNER JOIN
DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DEPT.DEPTNO = 4;

-- 10)
SHOW COLUMNS FROM JOB_GRADES;
SELECT EMP.EFNAME, EMP.JOB, DEPT.DNAME, EMP.SAL, JOB_GRADES.GRADE
FROM EMP
INNER JOIN
DEPT ON EMP.DEPTNO = DEPT.DEPTNO
INNER JOIN
JOB_GRADES ON EMP.JOB = JOB_GRADES.JOB;


-- 11)
SELECT EMP.EFNAME, JOB_GRADES.HIRE_DATE
FROM EMP
INNER JOIN
JOB_GRADES ON EMP.JOB = JOB_GRADES.JOB
WHERE JOB_GRADES.HIRE_DATE > '1999-10-10 12:00';
